title: Dominic Fanucchi
logo: "/images/portfolio_logo_1.jpeg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Machine Learning Engineer, currently earning a Master's Degree (Spring '25) in Applied Artificial Intelligence from the University of San Diego. 
  Welcome to my professional portfolio where you will find my personal projects, and projects I was involved in. I will be updating the site with my resume,
  as well as any of my writings.
  <br><br>
  Computer Science Bachelor's from California State University. 
  <br><br>
  <a href="https://www.linkedin.com/in/dominicfanucchi/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-31Q9TPYPP1
